name: torus_flutter_widgets
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  intl: any
  timezone: ^0.10.0
  expandable_datatable: ^0.0.7
  connectivity_plus: ^6.1.3
  flutter_bloc: any
  form_builder_validators: any
  responsive_grid: ^2.4.4
  pinput: any
  sms_autofill: ^2.4.1
  provider: ^6.1.2
  fl_chart: ^0.70.2
  graphic: ^2.5.1
  syncfusion_flutter_charts: ^28.2.11
  pie_chart: ^5.4.0
  circular_countdown_timer: ^0.2.4
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/image/upload.png
    - assets/dumb.json
    - assets/image/group.jpg
    - assets/image/pngtree4.png
    - assets/image/istockph.jpg
    - assets/image/BEAUTIFUL.png
    - assets/image/tumblr.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
